/* Generated By:JavaCC: Do not edit this line. FilterParserConstants.java */
package it.unimi.di.law.warc.filters.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int TRUE = 8;
  /** RegularExpression Id. */
  int FALSE = 9;
  /** RegularExpression Id. */
  int OPENPAREN = 10;
  /** RegularExpression Id. */
  int CLOSEPAREN = 11;
  /** RegularExpression Id. */
  int WORD = 12;
  /** RegularExpression Id. */
  int ARGS = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<TRUE>",
    "<FALSE>",
    "\"(\"",
    "\")\"",
    "<WORD>",
    "<ARGS>",
  };

}
